"""migrate with used column

Revision ID: 6a60a36471dc
Revises: 
Create Date: 2024-03-21 09:36:52.196726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a60a36471dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('clock_start', sa.String(), nullable=False),
    sa.Column('clock_stop', sa.String(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('stop', sa.Integer(), nullable=False),
    sa.Column('player', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('assist', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_plays_project_id_projects')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('play_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['play_id'], ['plays.id'], name=op.f('fk_games_play_id_plays')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('jersey', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('play_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['play_id'], ['plays.id'], name=op.f('fk_players_play_id_plays')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('play_game_table',
    sa.Column('play_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_play_game_table_game_id_games')),
    sa.ForeignKeyConstraint(['play_id'], ['plays.id'], name=op.f('fk_play_game_table_play_id_plays')),
    sa.PrimaryKeyConstraint('play_id', 'game_id')
    )
    op.create_table('play_player_table',
    sa.Column('play_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['play_id'], ['plays.id'], name=op.f('fk_play_player_table_play_id_plays')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_play_player_table_player_id_players')),
    sa.PrimaryKeyConstraint('play_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('play_player_table')
    op.drop_table('play_game_table')
    op.drop_table('players')
    op.drop_table('games')
    op.drop_table('plays')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
